[[miners]]
name = "rigel"

  [[miners.args]]
  flag = "--coin"
  field = "coin"

  [[miners.args]]
  flag = "--algorithm"
  field = "algorithm"

  [[miners.args]]
  flag = "--username"
  field = "wallet"

  [[miners.args]]
  flag = "--url"
  field = "pool"

  [[miners.args]]
  flag = "--worker"
  field = "worker"

  [[miners.args]]
  flag = "--cclock"
  field = "core_clock"

  [[miners.args]]
  flag = "--mclock"
  field = "mem_clock"

  [[miners.args]]
  flag = "--fan-control"
  field = "fan_speed"

  [[miners.args]]
  flag = "--pl"
  field = "power_limit"


[[miners]]
name = "trex"

  [[miners.args]]
  flag = "--coin"
  field = "coin"

  [[miners.args]]
  flag = "--algo"
  field = "algorithm"

  [[miners.args]]
  flag = "--url"
  field = "pool"

  [[miners.args]]
  flag = "--user"
  field = "wallet"

  [[miners.args]]
  flag = "--pass"
  field = "password"

  [[miners.args]]
  flag = "--fan"
  field = "fan_speed"

  [[miners.args]]
  flag = "--cclock"
  field = "core_clock"

  [[miners.args]]
  flag = "--mclock"
  field = "mem_clock"

  [[miners.args]]
  flag = "--pl"
  field = "power_limit"

[[miners]]
name = "lolMiner"

  [[miners.args]]
  flag = "--coin"
  field = "coin"

  [[miners.args]]
  flag = "--algo"
  field = "algorithm"

  [[miners.args]]
  flag = "--url"
  field = "pool"

  [[miners.args]]
  flag = "--user"
  field = "wallet"

  [[miners.args]]
  flag = "--pass"
  field = "password"

  [[miners.args]]
  flag = "--fan"
  field = "fan_speed"

  [[miners.args]]
  flag = "--cclk"
  field = "core_clock"

  [[miners.args]]
  flag = "--mclk"
  field = "mem_clock"

  [[miners.args]]
  flag = "--pl"
  field = "power_limit"

[[miners]]
  name = "xmrig"

  [[miners.args]]
  flag = "--coin"
  field = "coin"

  [[miners.args]]
  flag = "--url"
  field = "pool"

  [[miners.args]]
  flag = "--user"
  field = "wallet"

  [[miners.args]]
  flag = "--rig-id"
  field = "worker"

[[miners]]
name = "miniz"

  [[miners.args]]
  flag = "--algo"
  field = "algorithm"

  [[miners.args]]
  flag = "--url"
  field = "pool"

  [[miners.args]]
  flag = "--user"
  field = "wallet"

  [[miners.args]]
  flag = "--worker"
  field = "worker"

  [[miners.args]]
  flag = "--cclock"
  field = "core_clock"

  [[miners.args]]
  flag = "--mclock"
  field = "mem_clock"

  [[miners.args]]
  flag = "--fan"
  field = "fan_speed"

  [[miners.args]]
  flag = "--pl"
  field = "power_limit"

[[miners]]
name = "wildrig"

  [[miners.args]]
  flag = "--algo"
  field = "algorithm"

  [[miners.args]]
  flag = "--url"
  field = "pool"

  [[miners.args]]
  flag = "--user"
  field = "wallet"

  [[miners.args]]
  flag = "--pass"
  field = "worker"

  [[miners.args]]
  flag = "--cclock"
  field = "core_clock"

  [[miners.args]]
  flag = "--mclock"
  field = "mem_clock"

  [[miners.args]]
  flag = "--fan"
  field = "fan_speed"

  [[miners.args]]
  flag = "--pl"
  field = "power_limit"

[[miners]]
name = "miner"# gminer

[[miners.args]]
flag = "--algo"
field = "algorithm"

[[miners.args]]
flag = "--server"
field = "pool"

[[miners.args]]
flag = "--user"
field = "wallet"

[[miners.args]]
flag = "--pass"
field = "worker"

[[miners.args]]
flag = "--cclock"
field = "core_clock"

[[miners.args]]
flag = "--mclock"
field = "mem_clock"

[[miners.args]]
flag = "--fan"
field = "fan_speed"

[[miners.args]]
flag = "--pl"
field = "power_limit"

[[miners]]
name = "teamredminer"

[[miners.args]]
flag = "--algo"
field = "algorithm"

[[miners.args]]
flag = "-o"
field = "pool"

[[miners.args]]
flag = "-u"
field = "wallet"

[[miners.args]]
flag = "-p"
field = "worker"

[[miners.args]]
flag = "--cclock"
field = "core_clock"

[[miners.args]]
flag = "--mclock"
field = "mem_clock"

[[miners.args]]
flag = "--fan"
field = "fan_speed"

[[miners.args]]
flag = "--power-limit"
field = "power_limit"

[[miners]]
name = "phoenixminer"

[[miners.args]]
flag = "-coin"
field = "coin"

[[miners.args]]
flag = "-pool"
field = "pool"

[[miners.args]]
flag = "-wal"
field = "wallet"

[[miners.args]]
flag = "-worker"
field = "worker"

[[miners.args]]
flag = "-cclock"
field = "core_clock"

[[miners.args]]
flag = "-mclock"
field = "mem_clock"

[[miners.args]]
flag = "-fan"
field = "fan_speed"

[[miners.args]]
flag = "-powlim"
field = "power_limit"

[[miners]]
name = "srbminer"

[[miners.args]]
flag = "--algorithm"
field = "algorithm"

[[miners.args]]
flag = "--pool"
field = "pool"

[[miners.args]]
flag = "--wallet"
field = "wallet"

[[miners.args]]
flag = "--worker"
field = "worker"

[[miners.args]]
flag = "--cclock"
field = "core_clock"

[[miners.args]]
flag = "--mclock"
field = "mem_clock"

[[miners.args]]
flag = "--fan"
field = "fan_speed"

[[miners.args]]
flag = "--pl"
field = "power_limit"

[[miners]]
name = "bzminer"

[[miners.args]]
flag = "--algo"
field = "algorithm"

[[miners.args]]
flag = "--url"
field = "pool"

[[miners.args]]
flag = "--user"
field = "wallet"

[[miners.args]]
flag = "--worker"
field = "worker"

[[miners.args]]
flag = "--cclock"
field = "core_clock"

[[miners.args]]
flag = "--mclock"
field = "mem_clock"

[[miners.args]]
flag = "--fan"
field = "fan_speed"

[[miners.args]]
flag = "--pl"
field = "power_limit"

[[miners]]
name = "nbminer"

[[miners.args]]
flag = "-a"
field = "algorithm"

[[miners.args]]
flag = "-o"
field = "pool"

[[miners.args]]
flag = "-u"
field = "wallet"

[[miners.args]]
flag = "-w"
field = "worker"

[[miners.args]]
flag = "--cclock"
field = "core_clock"

[[miners.args]]
flag = "--mclock"
field = "mem_clock"

[[miners.args]]
flag = "--fan"
field = "fan_speed"

[[miners.args]]
flag = "--pl"
field = "power_limit"